FROM node:20-alpine

WORKDIR /client

ARG REACT_APP_TINYMCE_API_KEY

COPY package.json package-lock.json ./

RUN npm install --silent

COPY . ./

RUN REACT_APP_TINYMCE_API_KEY=$REACT_APP_TINYMCE_API_KEY npm run build