services:
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: UTC
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: always
    depends_on:
      - database

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data

  server:
    restart: always
    build: ./server
    ports:
      - '8000:8000'
    volumes:
      - ./server:/server
      - ./vita-health-432601-d5ccd599a1ab.json:/server/config/vita-health-432601-d5ccd599a1ab.json:ro
    depends_on:
      - database
      - redis
      - elasticsearch
    environment:
      - SERVER_ENV=development
    env_file:
      - .env

  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.development
    ports:
      - '3000:3000'
    volumes:
      - /client/node_modules
      - ./client:/client
    depends_on:
      - server
    environment:
      WATCHPACK_POLLING: true
      REACT_APP_TINYMCE_API_KEY: ${TINYMCE_API_KEY}

volumes:
  mysql_data:
  redis_data:
  es_data: