services:
  client:
    restart: always
    build: ./client
    depends_on:
      - server

  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: UTC
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  server:
    restart: always
    build: ./server
    ports:
      - '8000:8000'
    depends_on:
      - database
    env_file:
      - .env

  nginx:
    restart: always
    build: .
    ports:
      - '80:80'
    depends_on:
      - client
      - server

volumes:
  mysql_data: