name: Deploy to VM

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to VM
      run: |
        scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.VM_USER }}@${{ secrets.VM_IP }}:./vita-health

    - name: Deploy on VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} << 'EOF'
        cd ./vita-health
        export MYSQL_USER=${{ secrets.MYSQL_USER }}
        export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
        export MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
        export HOST=${{ secrets.HOST }}
        export PORT=${{ secrets.PORT }}
        export FERNET_KEY=${{ secrets.FERNET_KEY }}
        export SECRET=${{ secrets.SECRET }}
        sudo docker compose down
        sudo docker compose up -d --build
        EOF
